export interface PhotoItem {
  id: string;
  title: string;
  category: 'artistas' | 'conciertos' | 'deportes' | 'destinos' | 'lifestyle' | 'marcas';
  categoryLabel: string;
  src: string;
  aspectRatio: 'portrait' | 'landscape' | 'square';
  role: string;
  camera: string;
  lens: string;
  focalLength: string;
  aperture: string;
  shutter: string;
  iso: string;
  location: string;
  year: string;
  client?: string;
  description: string;
  tags: string[];
}

export interface VideoItem {
  id: string;
  title: string;
  category: 'videoclips' | 'conciertos' | 'deportes' | 'destinos' | 'documental' | 'marcas' | 'redes';
  categoryLabel: string;
  streamUrl: string;
  localPath: string;
  posterUrl: string;
  aspectRatio: '16:9' | '9:16' | '4:3';
  duration: string;
  role: string;
  director: string;
  client: string;
  year: string;
  resolution: string;
  fps: string;
  colorGrade: string;
  description: string;
  tags: string[];
}

export const PHOTO_CATALOG: readonly PhotoItem[] = [
  // --- ARTISTAS ---
  {
    id: 'art-01',
    title: 'Dualidad & Silueta Urbana',
    category: 'artistas',
    categoryLabel: 'Artistas & Retratos',
    src: '/media/imagenes/artistas/DOBLEU_-11.webp',
    aspectRatio: 'portrait',
    role: 'Fotógrafo Principal',
    camera: 'Sony FX3 Cinema',
    lens: 'Sony FE 50mm f/1.2 GM',
    focalLength: '50mm',
    aperture: '1.4',
    shutter: '1/250s',
    iso: '100',
    location: 'Estudio Alpha / Caracas',
    year: '2026',
    client: 'WES Session',
    description: 'Iluminación de recorte y contraste duro en clave baja. Dirección de arte y composición geométrica en plano medio cerrado.',
    tags: ['Retrato', 'Estudio', 'Clave Baja', 'Editorial'],
  },
  {
    id: 'art-02',
    title: 'Visión Cromática / Backstage',
    category: 'artistas',
    categoryLabel: 'Artistas & Retratos',
    src: '/media/imagenes/artistas/DOBLEU_-13.webp',
    aspectRatio: 'portrait',
    role: 'Director de Fotografía',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 35mm f/1.4 GM',
    focalLength: '35mm',
    aperture: '1.8',
    shutter: '1/320s',
    iso: '200',
    location: 'Green Room Sessions',
    year: '2025',
    client: 'Gonzo & Friends',
    description: 'Captura espontánea entre tomas. Saturación controlada y ángulo picado para acentuar el dinamismo de la escena.',
    tags: ['Backstage', 'Música', 'Retrato', 'Atmósfera'],
  },
  {
    id: 'art-03',
    title: 'Editorial Monocromo III',
    category: 'artistas',
    categoryLabel: 'Artistas & Retratos',
    src: '/media/imagenes/artistas/DOBLEU_-16.webp',
    aspectRatio: 'portrait',
    role: 'Fotógrafo Editorial',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 85mm f/1.4 GM',
    focalLength: '85mm',
    aperture: '1.4',
    shutter: '1/500s',
    iso: '100',
    location: 'Caracas, VE',
    year: '2025',
    client: 'Colección Urbana',
    description: 'Enfoque selectivo sobre textura textil y mirada. Alta fidelidad de rango dinámico sin distorsión óptica.',
    tags: ['Editorial', 'Moda', 'Retrato'],
  },
  {
    id: 'art-04',
    title: 'Geometría Facial & Claroscuro',
    category: 'artistas',
    categoryLabel: 'Artistas & Retratos',
    src: '/media/imagenes/artistas/DOBLEU_-14.webp',
    aspectRatio: 'square',
    role: 'Director de Arte & Retratista',
    camera: 'Sony FX3 Cinema',
    lens: 'Sony FE 50mm f/1.2 GM',
    focalLength: '50mm',
    aperture: '2.0',
    shutter: '1/160s',
    iso: '160',
    location: 'Estudio Brutalista',
    year: '2026',
    client: 'WES Project',
    description: 'Composición de aristas vivas donde la sombra divide el cuadro en proporciones áureas precisas.',
    tags: ['Claroscuro', 'Estudio', 'Geometría'],
  },
  {
    id: 'art-05',
    title: 'Presencia Escénica',
    category: 'artistas',
    categoryLabel: 'Artistas & Retratos',
    src: '/media/imagenes/artistas/DOBLEU_-15.webp',
    aspectRatio: 'portrait',
    role: 'Fotoperiodista Musical',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 24-70mm f/2.8 GM II',
    focalLength: '70mm',
    aperture: '2.8',
    shutter: '1/400s',
    iso: '400',
    location: 'Teatro Municipal',
    year: '2025',
    client: 'Vocal Artist Live',
    description: 'Captura en tiempo real con iluminación estroboscópica ambiental y balance de blancos cinematográfico.',
    tags: ['Escena', 'Luz Natural', 'En vivo'],
  },

  // --- CONCIERTOS ---
  {
    id: 'conc-01',
    title: 'Éxtasis Colectivo / Live Energy',
    category: 'conciertos',
    categoryLabel: 'Conciertos & Eventos',
    src: '/media/imagenes/conciertos/DOBLEU_-01.webp',
    aspectRatio: 'landscape',
    role: 'Lead Live Photographer',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 16-35mm f/2.8 GM',
    focalLength: '16mm',
    aperture: '2.8',
    shutter: '1/640s',
    iso: '1600',
    location: 'Festival Anima Sunrise',
    year: '2025',
    client: 'Anima Producciones',
    description: 'Gran angular inmersivo en el punto álgido del show. Rayos láser suspendidos en niebla y multitud en silueta.',
    tags: ['Festival', 'Live', 'Láser', 'Crowd'],
  },
  {
    id: 'conc-02',
    title: 'Atmósfera Flowershop',
    category: 'conciertos',
    categoryLabel: 'Conciertos & Eventos',
    src: '/media/imagenes/conciertos/DOBLEU_-03.webp',
    aspectRatio: 'portrait',
    role: 'Fotógrafo Oficial',
    camera: 'Sony FX3 Cinema',
    lens: 'Sony FE 35mm f/1.4 GM',
    focalLength: '35mm',
    aperture: '1.8',
    shutter: '1/500s',
    iso: '800',
    location: 'The Flowershop Secret Stage',
    year: '2026',
    client: 'The Flowershop Project',
    description: 'Tratamiento de color cinematográfico con halación en luces altas y microcontraste en tonos medios.',
    tags: ['Aftermovie', 'Fiesta', 'Nocturno'],
  },
  {
    id: 'conc-03',
    title: 'Pura Frecuencia / DJ Set',
    category: 'conciertos',
    categoryLabel: 'Conciertos & Eventos',
    src: '/media/imagenes/conciertos/DOBLEU_-06.webp',
    aspectRatio: 'landscape',
    role: 'Director Visual de Escenario',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 24-70mm f/2.8 GM II',
    focalLength: '24mm',
    aperture: '2.8',
    shutter: '1/400s',
    iso: '1250',
    location: 'Timotes Sessions',
    year: '2025',
    client: 'Timotes Marciano Live',
    description: 'Sincronización milimétrica con la pirotecnia de cabina. Enfoque hiperfocal para mantener profundidad.',
    tags: ['DJ', 'Escenario', 'Pirotecnia'],
  },
  {
    id: 'conc-04',
    title: 'Vibración Frontal',
    category: 'conciertos',
    categoryLabel: 'Conciertos & Eventos',
    src: '/media/imagenes/conciertos/DOBLEU_-10.webp',
    aspectRatio: 'portrait',
    role: 'Fotógrafo de Gira',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 85mm f/1.4 GM',
    focalLength: '85mm',
    aperture: '1.4',
    shutter: '1/800s',
    iso: '2000',
    location: 'Noreh Concierto Íntimo',
    year: '2025',
    client: 'Noreh Tour',
    description: 'Aislación del artista en tarima principal. Desenfoque cremoso en el bokeh de las luces de fondo.',
    tags: ['Concierto', 'Emoción', 'Live'],
  },

  // --- DEPORTES ---
  {
    id: 'dep-01',
    title: 'Agarre & Tensión / BJJ Finals',
    category: 'deportes',
    categoryLabel: 'Acción & Deportes',
    src: '/media/imagenes/deportes/DOBLEU_-079.JPG.webp',
    aspectRatio: 'landscape',
    role: 'Fotógrafo de Deportes de Combate',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 70-200mm f/2.8 GM OSS II',
    focalLength: '135mm',
    aperture: '2.8',
    shutter: '1/1600s',
    iso: '1600',
    location: 'Torneo Nacional de Jiu-Jitsu',
    year: '2025',
    client: 'Federación BJJ',
    description: 'Velocidad de obturación ultrarrápida para congelar las gotas de sudor y la tensión muscular en el tatami.',
    tags: ['BJJ', 'Deportes', 'Acción', 'Artes Marciales'],
  },
  {
    id: 'dep-02',
    title: 'Impacto & Enfoque Atlético',
    category: 'deportes',
    categoryLabel: 'Acción & Deportes',
    src: '/media/imagenes/deportes/DOBLEU_-084.JPG.webp',
    aspectRatio: 'portrait',
    role: 'Fotógrafo de Alto Rendimiento',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 70-200mm f/2.8 GM OSS II',
    focalLength: '200mm',
    aperture: '2.8',
    shutter: '1/2000s',
    iso: '800',
    location: 'Complejo Deportivo Central',
    year: '2025',
    client: 'Furia Team Athletes',
    description: 'Enfoque al ojo continuo en ráfaga de alta velocidad. Textura y determinación en la mirada competitiva.',
    tags: ['Atletas', 'Entrenamiento', 'Fuerza'],
  },
  {
    id: 'dep-03',
    title: 'Motocross / Vuelo en Polvo',
    category: 'deportes',
    categoryLabel: 'Acción & Deportes',
    src: '/media/imagenes/deportes/DOBLEU_-152.webp',
    aspectRatio: 'landscape',
    role: 'Fotógrafo de Deportes Extremos',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 24-70mm f/2.8 GM II',
    focalLength: '35mm',
    aperture: '4.0',
    shutter: '1/3200s',
    iso: '400',
    location: 'Pista Furia Club',
    year: '2026',
    client: 'Motocross Championship',
    description: 'Toma angular a ras de suelo en el momento del salto. La nube de tierra enmarca la silueta de la moto.',
    tags: ['Motocross', 'Polvo', 'Extremo', 'Velocidad'],
  },
  {
    id: 'dep-04',
    title: 'Padel / Precisión en Volea',
    category: 'deportes',
    categoryLabel: 'Acción & Deportes',
    src: '/media/imagenes/deportes/DOBLEU_-239.webp',
    aspectRatio: 'portrait',
    role: 'Fotógrafo de Circuito Deportivo',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 85mm f/1.4 GM',
    focalLength: '85mm',
    aperture: '2.0',
    shutter: '1/2500s',
    iso: '320',
    location: 'Padel Club Pro',
    year: '2025',
    client: 'Circuito Nacional Padel',
    description: 'Congelamiento exacto de la pelota en contacto con la pala de carbono y reflejo en cristal de la cancha.',
    tags: ['Padel', 'Precisión', 'Acción'],
  },

  // --- DESTINOS NACIONALES ---
  {
    id: 'dest-01',
    title: 'Horizonte Caribeño / Shangri-La',
    category: 'destinos',
    categoryLabel: 'Destinos & Paisajes',
    src: '/media/imagenes/destinos/DOBLEU_-072.webp',
    aspectRatio: 'landscape',
    role: 'Fotógrafo de Paisajes & Ecoturismo',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 16-35mm f/2.8 GM',
    focalLength: '16mm',
    aperture: '8.0',
    shutter: '1/200s',
    iso: '100',
    location: 'Shangri-La Eco Resort',
    year: '2025',
    client: 'Turismo Venezuela',
    description: 'Composición paisajística con polarizador circular. Texturas marinas y nubes en alta definición.',
    tags: ['Caribe', 'Paisaje', 'Naturaleza', 'Océano'],
  },
  {
    id: 'dest-02',
    title: 'Cromática Costera',
    category: 'destinos',
    categoryLabel: 'Destinos & Paisajes',
    src: '/media/imagenes/destinos/DOBLEU_-109.JPG.webp',
    aspectRatio: 'portrait',
    role: 'Director de Expedición Visual',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 24-70mm f/2.8 GM II',
    focalLength: '24mm',
    aperture: '5.6',
    shutter: '1/500s',
    iso: '100',
    location: 'Isla de Margarita',
    year: '2025',
    client: 'Expedición Costera',
    description: 'Luz dorada de atardecer bañando la costa rocosa con degradado suave en cielo y agua.',
    tags: ['Atardecer', 'Costa', 'Golden Hour'],
  },
  {
    id: 'dest-03',
    title: 'Perspectiva Aérea & Relieve',
    category: 'destinos',
    categoryLabel: 'Destinos & Paisajes',
    src: '/media/imagenes/destinos/DOBLEU_-162.JPG.webp',
    aspectRatio: 'landscape',
    role: 'Operador de Drone & Fotógrafo Aéreo',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 16-35mm f/2.8 GM',
    focalLength: '20mm',
    aperture: '7.1',
    shutter: '1/320s',
    iso: '100',
    location: 'Parque Nacional Mochima',
    year: '2025',
    client: 'Destinos Nacionales',
    description: 'Contraste entre la cordillera verde esmeralda y el azul profundo del mar caribeño.',
    tags: ['Mochima', 'Aéreo', 'Paisajes'],
  },

  // --- LIFESTYLE ---
  {
    id: 'life-01',
    title: 'Sombra & Estilo Callejero',
    category: 'lifestyle',
    categoryLabel: 'Estilo de Vida & Editorial',
    src: '/media/imagenes/lifestyle/DSC08434.JPG.webp',
    aspectRatio: 'portrait',
    role: 'Fotógrafo Streetwear',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 35mm f/1.4 GM',
    focalLength: '35mm',
    aperture: '1.4',
    shutter: '1/1000s',
    iso: '100',
    location: 'Distrito Urbano / Caracas',
    year: '2025',
    client: 'Streetwear Label',
    description: 'Estética documental contemporánea con juego de líneas duras y sombras proyectadas en hormigón.',
    tags: ['Streetwear', 'Urbano', 'Moda', 'Sombras'],
  },
  {
    id: 'life-02',
    title: 'Corte Editorial / Texturas',
    category: 'lifestyle',
    categoryLabel: 'Estilo de Vida & Editorial',
    src: '/media/imagenes/lifestyle/DSC08467.JPG.webp',
    aspectRatio: 'portrait',
    role: 'Director Creativo de Moda',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 50mm f/1.2 GM',
    focalLength: '50mm',
    aperture: '1.8',
    shutter: '1/800s',
    iso: '100',
    location: 'Galería de Arte Contemporáneo',
    year: '2025',
    client: 'Editorial Independiente',
    description: 'Encuadre asimétrico que desafía las reglas convencionales para generar tensión visual vanguardista.',
    tags: ['Moda', 'Editorial', 'Arte', 'Vanguardia'],
  },
  {
    id: 'life-03',
    title: 'Transeúnte / Silueta Dorada',
    category: 'lifestyle',
    categoryLabel: 'Estilo de Vida & Editorial',
    src: '/media/imagenes/lifestyle/DSC08479.JPG.webp',
    aspectRatio: 'landscape',
    role: 'Fotógrafo Documental',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 35mm f/1.4 GM',
    focalLength: '35mm',
    aperture: '2.0',
    shutter: '1/1250s',
    iso: '100',
    location: 'Avenida Principal',
    year: '2025',
    client: 'Personal Project',
    description: 'Contraluz perfecto que siluetea la figura humana contra el reflejo del pavimento caliente.',
    tags: ['Contraluz', 'Silueta', 'Urbano'],
  },

  // --- MARCAS ---
  {
    id: 'brand-01',
    title: 'Campaña Furia Gear / Vol. 4',
    category: 'marcas',
    categoryLabel: 'Marcas & Comercial',
    src: '/media/imagenes/marcas/DOBLEU_-040.JPG.webp',
    aspectRatio: 'landscape',
    role: 'Director de Campaña Comercial',
    camera: 'Sony FX3 Cinema',
    lens: 'Sony FE 24-70mm f/2.8 GM II',
    focalLength: '45mm',
    aperture: '2.8',
    shutter: '1/640s',
    iso: '200',
    location: 'Set Industrial',
    year: '2026',
    client: 'Furia Gear Oficial',
    description: 'Dirección de arte comercial de alto impacto con gradiente de iluminación técnica sobre producto.',
    tags: ['Comercial', 'Furia Gear', 'Producto', 'Campaña'],
  },
  {
    id: 'brand-02',
    title: 'Devant Eyewear / Vanguard',
    category: 'marcas',
    categoryLabel: 'Marcas & Comercial',
    src: '/media/imagenes/marcas/DOBLEU_-043.JPG.webp',
    aspectRatio: 'portrait',
    role: 'Fotógrafo de Producto & Moda',
    camera: 'Sony A7 IV',
    lens: 'Sony FE 85mm f/1.4 GM',
    focalLength: '85mm',
    aperture: '2.0',
    shutter: '1/500s',
    iso: '100',
    location: 'Estudio Minimal',
    year: '2026',
    client: 'Devant Eyewear',
    description: 'Fotografía de producto editorial con reflejos de luz controlados y nitidez quirúrgica en monturas.',
    tags: ['Devant', 'Moda', 'Gafas', 'Comercial'],
  },
  {
    id: 'brand-03',
    title: 'Papelón Mundial / Branding',
    category: 'marcas',
    categoryLabel: 'Marcas & Comercial',
    src: '/media/imagenes/marcas/DOBLEU_-048.JPG.webp',
    aspectRatio: 'landscape',
    role: 'Fotógrafo Gastronómico & Branding',
    camera: 'Sony FX3 Cinema',
    lens: 'Sony FE 50mm f/1.2 GM',
    focalLength: '50mm',
    aperture: '1.4',
    shutter: '1/800s',
    iso: '100',
    location: 'Caracas, VE',
    year: '2025',
    client: 'Papelón Mundial',
    description: 'Fotografía gastronómica y de marca con énfasis en frescura, condensación y paleta de acentos.',
    tags: ['Branding', 'Gastronomía', 'Bebidas'],
  },
];

export const VIDEO_CATALOG: readonly VideoItem[] = [
  // --- VIDEOCLIPS ---
  {
    id: 'vid-clip-01',
    title: 'Making Of: Baila',
    category: 'videoclips',
    categoryLabel: 'Videoclips Musicales',
    streamUrl: '/media/videos/videoclips/6MAKING_BAILA.webm',
    localPath: 'videoclips/6MAKING_BAILA.webm',
    posterUrl: '/media/imagenes/artistas/DOBLEU_-11.webp',
    aspectRatio: '16:9',
    duration: '02:45',
    role: 'Director de Fotografía & Edición',
    director: 'WES',
    client: 'Gonzo / Sony Music Latam',
    year: '2026',
    resolution: '4K DCI (3840 x 2160)',
    fps: '24.000 fps',
    colorGrade: 'ACEScct / Film Emulation Kodachrome',
    description: 'Proceso de rodaje cinematográfico, iluminación dinámica, cámara en mano y dirección de actores en set principal.',
    tags: ['Videoclip', 'Making Of', '4K', 'Música'],
  },
  {
    id: 'vid-clip-02',
    title: 'Baila: Secuencia y Ritmo',
    category: 'videoclips',
    categoryLabel: 'Videoclips Musicales',
    streamUrl: '/media/videos/videoclips/7MAKING_BAILA.webm',
    localPath: 'videoclips/7MAKING_BAILA.webm',
    posterUrl: '/media/imagenes/artistas/DOBLEU_-13.webp',
    aspectRatio: '16:9',
    duration: '03:10',
    role: 'Director & Colorista',
    director: 'WES',
    client: 'Producción Musical Indie',
    year: '2026',
    resolution: '4K Ultra HD',
    fps: '48.000 fps (Cámara Lenta)',
    colorGrade: 'DaVinci Wide Gamut',
    description: 'Tomas coreográficas con ritmo visual trepidante y montaje sincopado en corte directo.',
    tags: ['Coreografía', 'Danza', 'Color'],
  },

  // --- MARCAS ---
  {
    id: 'vid-brand-01',
    title: 'Furia Gear: Vol. 4 Reel Comercial',
    category: 'marcas',
    categoryLabel: 'Comerciales & Marcas',
    streamUrl: '/media/videos/marcas/2_reel_furia_gear.webm',
    localPath: 'marcas/2_reel_furia_gear.webm',
    posterUrl: '/media/imagenes/marcas/DOBLEU_-040.JPG.webp',
    aspectRatio: '9:16',
    duration: '00:45',
    role: 'Cinematógrafo & Editor',
    director: 'WES',
    client: 'Furia Gear Global',
    year: '2026',
    resolution: 'Vertical 4K (2160 x 3840)',
    fps: '60.000 fps',
    colorGrade: 'High Contrast Tactical Black',
    description: 'Spot dinámico para plataformas móviles. Montaje acelerado, transiciones invisibles por whip pan y tipografía geométrica.',
    tags: ['Reel', 'Comercial', 'Furia Gear', 'Vertical'],
  },
  {
    id: 'vid-brand-02',
    title: 'Camisas Michi: Summer Line',
    category: 'marcas',
    categoryLabel: 'Comerciales & Marcas',
    streamUrl: '/media/videos/marcas/CAMISAS_MICHI_1.webm',
    localPath: 'marcas/CAMISAS_MICHI_1.webm',
    posterUrl: '/media/imagenes/marcas/DOBLEU_-043.JPG.webp',
    aspectRatio: '9:16',
    duration: '01:15',
    role: 'Director Creativo',
    director: 'WES',
    client: 'Michi Apparel',
    year: '2025',
    resolution: 'Full HD Vertical',
    fps: '30.000 fps',
    colorGrade: 'Tropical Vintage Kodak 250D',
    description: 'Campaña de verano con estética analógica fresca y plano secuencia en movimiento fluido.',
    tags: ['Moda', 'Verano', 'Textil'],
  },

  // --- REDES SOCIALES ---
  {
    id: 'vid-red-01',
    title: 'Black Stacy Malibu: Edición Limitada',
    category: 'redes',
    categoryLabel: 'Social Media & Reels',
    streamUrl: '/media/videos/redes/BLK_STACY_MALIBU_3.webm',
    localPath: 'redes/BLK_STACY_MALIBU_3.webm',
    posterUrl: '/media/imagenes/lifestyle/DSC08434.JPG.webp',
    aspectRatio: '9:16',
    duration: '00:35',
    role: 'Realizador Audiovisual',
    director: 'WES',
    client: 'Stacy Brand',
    year: '2026',
    resolution: '1080 x 1920 HD',
    fps: '60.000 fps',
    colorGrade: 'Monochrome Acid Highlight',
    description: 'Microcontenido viral de alto impacto con sonido inmersivo y cortes sincrónicos al beat.',
    tags: ['Viral', 'Reels', 'TikTok', 'Moda'],
  },
  {
    id: 'vid-red-02',
    title: 'Cartel 1: Street Art & Vibes',
    category: 'redes',
    categoryLabel: 'Social Media & Reels',
    streamUrl: '/media/videos/redes/CARTEL_1.webm',
    localPath: 'redes/CARTEL_1.webm',
    posterUrl: '/media/imagenes/lifestyle/DSC08467.JPG.webp',
    aspectRatio: '9:16',
    duration: '00:40',
    role: 'Filmmaker & Editor',
    director: 'WES',
    client: 'Festival de Arte Urbano',
    year: '2025',
    resolution: '1080 x 1920 HD',
    fps: '24.000 fps',
    colorGrade: 'Urban Gritty Film Look',
    description: 'Cápsula cinematográfica para Instagram Reels con estética analógica y grano de 35mm.',
    tags: ['Street Art', 'Reel', 'Grano'],
  },
  {
    id: 'vid-red-03',
    title: 'Chelonia: Campaña Océano',
    category: 'redes',
    categoryLabel: 'Social Media & Reels',
    streamUrl: '/media/videos/redes/CHELONIA_2_1.webm',
    localPath: 'redes/CHELONIA_2_1.webm',
    posterUrl: '/media/imagenes/destinos/DOBLEU_-072.webp',
    aspectRatio: '9:16',
    duration: '01:05',
    role: 'Director de Fotografía Submarina',
    director: 'WES',
    client: 'Chelonia Ecoturismo',
    year: '2025',
    resolution: '4K Vertical',
    fps: '60.000 fps',
    colorGrade: 'Deep Ocean Blue LUT',
    description: 'Secuencias acuáticas y aéreas de conservación marina con narrativa cautivadora.',
    tags: ['Océano', 'Acuático', 'Drone'],
  },

  // --- CONCIERTOS ---
  {
    id: 'vid-conc-01',
    title: 'Anima Sunrise: Official Aftermovie',
    category: 'conciertos',
    categoryLabel: 'Conciertos & Festivales',
    streamUrl: '/media/videos/conciertos/ANIMA_SUNRISE.webm',
    localPath: 'conciertos/ANIMA_SUNRISE.webm',
    posterUrl: '/media/imagenes/conciertos/DOBLEU_-01.webp',
    aspectRatio: '16:9',
    duration: '03:40',
    role: 'Lead Cinematographer & Director',
    director: 'WES',
    client: 'Anima Festival Group',
    year: '2025',
    resolution: '4K Widescreen 2.39:1',
    fps: '60.000 / 24.000 fps',
    colorGrade: 'Neon Cyberpunk Palette',
    description: 'Recap cinematográfico con estabilización gimbal Ronin RS3, multicámara y master de audio directo de mesa.',
    tags: ['Aftermovie', 'Festival', 'EDM', 'Láser'],
  },

  // --- DEPORTES ---
  {
    id: 'vid-dep-01',
    title: '8va Válida Nacional: Intro Cinematográfica',
    category: 'deportes',
    categoryLabel: 'Deportes Extremos',
    streamUrl: '/media/videos/deportes/8VA_VALIDA_INTRO.webm',
    localPath: 'deportes/8VA_VALIDA_INTRO.webm',
    posterUrl: '/media/imagenes/deportes/DOBLEU_-152.webp',
    aspectRatio: '16:9',
    duration: '01:50',
    role: 'Director & Operador de Alta Velocidad',
    director: 'WES',
    client: 'Federación Nacional de Motociclismo',
    year: '2025',
    resolution: 'ProRes 422 HQ 4K',
    fps: '120.000 fps Slow Motion',
    colorGrade: 'High Dynamic Range Mud & Sky',
    description: 'Pieza de apertura para transmisión en vivo. Macro de motores, cadenas, salida en valla y vuelo en pista.',
    tags: ['Motocross', 'Intro', 'ProRes', 'Slow Motion'],
  },
  {
    id: 'vid-dep-02',
    title: 'BJJ: El Arte Suave',
    category: 'deportes',
    categoryLabel: 'Deportes Extremos',
    streamUrl: '/media/videos/deportes/BJJ.webm',
    localPath: 'deportes/BJJ.webm',
    posterUrl: '/media/imagenes/deportes/DOBLEU_-079.JPG.webp',
    aspectRatio: '16:9',
    duration: '02:15',
    role: 'Cinematógrafo Documental',
    director: 'WES',
    client: 'Academia Gracie Barra',
    year: '2025',
    resolution: '4K Ultra HD',
    fps: '24.000 fps',
    colorGrade: 'Gritty Monochromatic Split Tone',
    description: 'Mini documental sobre la disciplina, respiración y filosofía de los atletas de combate.',
    tags: ['BJJ', 'Documental', 'Filosofía'],
  },

  // --- DOCUMENTAL ---
  {
    id: 'vid-doc-01',
    title: 'Día del Niño: Sonrisas en la Costa',
    category: 'documental',
    categoryLabel: 'Documental Social',
    streamUrl: '/media/videos/documental/DIA_DEL_NIÑO_V1.webm',
    localPath: 'documental/DIA_DEL_NIÑO_V1.webm',
    posterUrl: '/media/imagenes/lifestyle/DSC08490.JPG.webp',
    aspectRatio: '16:9',
    duration: '03:30',
    role: 'Director & Fotógrafo Documental',
    director: 'WES',
    client: 'Fundación Manos a la Costa',
    year: '2025',
    resolution: '4K Cinema',
    fps: '24.000 fps',
    colorGrade: 'Natural Warm Sunlit',
    description: 'Documental de impacto social en comunidades pesqueras. Entrevistas espontáneas y retrato humano con luz natural.',
    tags: ['Social', 'Documental', 'Costa', 'Comunidad'],
  },
];

export const ARTIST_PROFILE = {
  name: 'WES',
  role: 'Fotógrafo & Director de Fotografía Audiovisual',
  location: 'Caracas, Venezuela • Disponible Globalmente',
  bio: `Creador audiovisual y director de fotografía con más de 7 años de trayectoria capturando la energía cruda de la música en vivo, campañas de marcas internacionales, retratos de alta costura y deportes extremos. Mi visión artística se fundamenta en la precisión geométrica, el contraste agresivo en claroscuro y la autenticidad sin filtros.`,
  trajectory: [
    {
      year: '2024 - 2026',
      title: 'Director Audiovisual & Lead Cinematographer',
      company: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      year: '2022 - 2024',
      title: 'Fotógrafo Comercial & Editor de Moda',
      company: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
      year: '2019 - 2022',
      title: 'Fotoperiodista de Acción & Deportes Extremos',
      company: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      description: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    },
  ],
  gear: [
    { category: 'Cámaras Principales', items: ['Sony FX3 Cinema Line (4K 120fps 10-bit 4:2:2)', 'Sony A7 IV (33MP Full Frame)', 'RED Komodo 6K Cinema Body'] },
    { category: 'Óptica & Lentes Prime', items: ['Sony FE 50mm f/1.2 G Master', 'Sony FE 35mm f/1.4 G Master', 'Sony FE 85mm f/1.4 G Master', 'Sony FE 16-35mm f/2.8 GM', 'Sony FE 70-200mm f/2.8 GM OSS II'] },
    { category: 'Grip & Iluminación', items: ['Gimbal DJI RS3 Pro con LiDAR Focus', 'Luces Aputure 600d Pro + Amaran RGB', 'Filtros PolarPro Peter McKinnon Variable ND', 'Audio Sennheiser MKH 416 + Drones DJI Mavic 3 Cine'] },
  ],
  stats: [
    { number: '120+', label: 'Proyectos Completados' },
    { number: '45+', label: 'Videoclips & Spots Dirigidos' },
    { number: '15+', label: 'Marcas Globales' },
    { number: '5+', label: 'Años de Trayectoria' },
  ],
  clients: [
    'FURIA GEAR',
    'NOREH / SONY LATAM',
    'DEVANT EYEWEAR',
    'ANIMA FESTIVAL',
    'THE FLOWERSHOP',
    'BJJ FEDERATION',
    'CHELONIA',
    'STACY MALIBU',
    'PAPELÓN MUNDIAL',
  ],
  socials: {
    instagram: 'https://instagram.com',
    vimeo: 'https://vimeo.com',
    youtube: 'https://youtube.com',
    behance: 'https://behance.net',
    email: 'contacto@wesfotografia.com',
    phone: '+58 412 000 0000',
    whatsapp: 'https://wa.me/584120000000',
  },
};
